trials/urls.py
from django.contrib import admin
from django.conf.urls.defaults import patterns, include, url

import trials.apps.people.views
import trials.apps.exercises.views

# See: https://docs.djangoproject.com/en/dev/ref/contrib/admin/#hooking-adminsite-instances-into-your-urlconf
admin.autodiscover()


# See: https://docs.djangoproject.com/en/dev/topics/http/urls/
urlpatterns = patterns('',
    # Admin panel and documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^$', 'apps.core.views.index'),
    url(r'^about$', 'apps.core.views.about'),
    url(r'^contact$', 'apps.core.views.contact'),

    # Students
    url(r'^students$', trials.apps.people.views.StudentList.as_view(),
        name='student_list'),
    url(r'^students/(?P<pk>\w+)$',
        trials.apps.people.views.StudentDetail.as_view(),
        name='student_detail'),

    url(r'exercises$', trials.apps.exercises.views.ExerciseList.as_view(),
        name='exercise_list'),
    url(r'exercises/(?P<pk>\w+)$',
        trials.apps.exercises.views.ExerciseDetail.as_view(),
        name='exercise_detail'),
)

trials/apps/core/models.py
from django.db import models

# Create your models here.

trials/apps/exercises/models.py
from datetime import datetime

from django.db import models

from trials.apps.people.models import Student


class Exercise(models.Model):
    """
    An exercise is made up of a set of trails.
    """
    # FIelds: Name, description, date,
    #   teacher, student, set of trials

    name = models.CharField(max_length=256)
    description = models.TextField()
    student = models.ForeignKey(Student)
    datetime = models.DateTimeField(auto_now_add=True, default=datetime.now)

    def __unicode__(self):
        return unicode(self.name)


class Trial(models.Model):
    """
    An individual trial
    """
    success = models.BooleanField()
    prompted = models.BooleanField()

    exercise = models.ForeignKey(Exercise)

    def __unicode__(self):
        if self.success and self.prompted:
            return u'++'
        elif self.success and not self.prompted:
            return u'+-'
        elif not self.success and self.prompted:
            return u'-+'
        else:
            return u'--'

trials/apps/people/models.py
from django.db import models

from trials.apps.schools.models import School


class Person(models.Model):
    """
    Base class for student, teacher, parent
    """
    first_name = models.CharField(max_length=256)
    last_name = models.CharField(max_length=256)

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)


class Teacher(Person):
    """
    Teacher
    """
    # Fields: school, ...
    email = models.EmailField()
    phone = models.CharField(max_length=10)

    # SHould their be a many to one field for students?


class Student(Person):
    """
    Student
    """
    # Fields: grade, school, teacher, ...
    grade = models.PositiveIntegerField()
    teacher = models.ForeignKey(Teacher)
    school = models.ForeignKey(School)

trials/apps/schools/models.py
from django.db import models


class School(models.Model):
    """
    """
    name = models.CharField(max_length=512)
    address = models.TextField()
    homepage = models.URLField()

    def __unicode__(self):
        return unicode(self.name)

trials/apps/core/views.py
# stardard library imports

# django imports
from django.http import Http404, HttpResponse
from django.template import Context, loader
from django.shortcuts import render_to_response


def index(request):
    """
    The homepage.
    """
    return render_to_response('index.html')


def about(request):
    """
    The about page.
    """
    return render_to_response('about.html')


def contact(request):
    """
    The contact page.
    """
    return render_to_response('contact.html')

trials/apps/exercises/views.py
# stardard library imports

# django imports
from django.views.generic import (CreateView,
                                  DeleteView,
                                  DetailView,
                                  ListView,
                                  UpdateView)

from trials.apps.exercises.models import Exercise


class ExerciseList(ListView):
    model = Exercise
    template_name = 'exercise_list.html'


class ExerciseDetail(DetailView):
    model = Exercise
    template_name = 'exercise_detail.html'

trials/apps/people/views.py
# stardard library imports

# django imports
from django.views.generic import (CreateView,
                                  DeleteView,
                                  DetailView,
                                  ListView,
                                  UpdateView)


from trials.apps.people.models import Teacher, Student


class StudentList(ListView):
    model = Student
    template_name = 'student_list.html'


class StudentDetail(DetailView):
    model = Student
    template_name = 'student_detail.html'

trials/apps/schools/views.py
# Create your views here.

trials/templates/about.html
{% extends "base.html" %}
{% block title %}About Trials...{% endblock %}
{% block content %}
  <p>
    Helping track and understand your child's progress in education.
  </p>
{% endblock %}

trials/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Trials</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    {% load static %}
    {% get_static_prefix as STATIC_PREFIX %}
    <link href="{{ STATIC_PREFIX }}css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="{{ STATIC_PREFIX }}css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Trials</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="about">About</a></li>
              <li><a href="contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div id="heading" class="container">
      <h1>{% block title %}Welcome to Trials!{% endblock %}</h1>
      <p></p>
    </div>
    <div id="content" class="container">
        {% block content %}{% endblock %}
    </div>
     <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ STATIC_PREFIX }}js/bootstrap.js"></script>

  </body>
</html>

trials/templates/contact.html
{% extends "base.html" %}
{% block title %}{% endblock %}
{% block content %}
  <p>
    For more information, contact...
  </p>
{% endblock %}

trials/templates/exercise_detail.html
{% extends "base.html" %}
{% block title %}{{ exercise }}{% endblock %}
{% block content %}
  <p></p>
  <p>{{ exercise.description }}</p>
    <script src="{{ STATIC_PREFIX }}js/Chart.js"></script>
    <meta name = "viewport" content = "initial-scale = 1, user-scalable = no">
    <style>
      canvas{}
    </style>
    <body>
      <canvas id="canvas" height="450" width="600"></canvas>
      <script> 
                var barChartData = {
                        labels : ["January","February","March","April","May","June","July"],
                        datasets : [
                                {
                                        fillColor : "rgba(220,220,220,0.5)",
                                        strokeColor : "rgba(220,220,220,1)",
                                        data : [65,59,90,81,56,55,40]
                                },
                                {
                                        fillColor : "rgba(151,187,205,0.5)",
                                        strokeColor : "rgba(151,187,205,1)",
                                        data : [28,48,40,19,96,27,100]
                                }
                        ]
                        
                }

        var myLine = new Chart(document.getElementById("canvas").getContext("2d")).Bar(barChartData);
      </script>
{% endblock %}

trials/templates/index.html
{% extends "base.html" %}
{% block content %}
{% endblock %}

trials/templates/student.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Trials</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    {% load static %}
    {% get_static_prefix as STATIC_PREFIX %}
    <link href="{{ STATIC_PREFIX }}css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="{{ STATIC_PREFIX }}css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Trials</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="about">About</a></li>
              <li><a href="contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <h1>{{ student }}</h1>
      <p></p>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>School</th>
              <th>Grade</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><a href="/students/{{ student.id }}">{{ student }}</a></td>
              <td>{{ student.school }}</td>
              <td>{{ student.grade  }}</td>
            </tr>
          </tbody>
        </table>
      <p></p>
      <h2>Programs</h2>
      <p></p>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>School</th>
              <th>Grade</th>
            </tr>
          </thead>
          <tbody>
          </tbody>
        </table>
      <p></p>
    </div>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ STATIC_PREFIX }}js/bootstrap.js"></script>

  </body>
</html>

trials/templates/student_detail.html
{% extends "base.html" %}
{% block title %}{{ student }}{% endblock %}
{% block content %}
  <p></p>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>School</th>
          <th>Grade</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><a href="/students/{{ student.id }}">{{ student }}</a></td>
          <td>{{ student.school }}</td>
          <td>{{ student.grade  }}</td>
        </tr>
      </tbody>
    </table>
  <p></p>
  <h2>Programs</h2>
  <p></p>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Name</th>
        </tr>
      </thead>
      <tbody>
        {% for e in student.exercise_set.all %}
          <tr>
            <td><a href="/exercises/{{ e.id }}">{{ e.name }}</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  <p></p>
{% endblock %}

trials/templates/student_list.html
{% extends "base.html" %}
{% block title %}Students{% endblock %}
{% block content %}
  <p></p>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Name</th>
          <th>School</th>
          <th>Grade</th>
        </tr>
      </thead>
      <tbody>
        {% if object_list %}
        {% for s in object_list %}
        <tr>
          <td><a href="/students/{{ s.id }}">{{ s }}</a></td>
          <td>{{ s.school }}</td>
          <td>{{ s.grade  }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
          <td></td>
          <td></td>
          <td></td>
        </tr>
        {% endif %}
      </tbody>
    </table>
  <p></p>
{% endblock %}

trials/templates/students.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Trials</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    {% load static %}
    {% get_static_prefix as STATIC_PREFIX %}
    <link href="{{ STATIC_PREFIX }}css/bootstrap.css" rel="stylesheet">
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>
    <link href="{{ STATIC_PREFIX }}css/bootstrap-responsive.css" rel="stylesheet">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

  </head>
  <body>

    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Trials</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="/">Home</a></li>
              <li><a href="about">About</a></li>
              <li><a href="contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <h1>Students</h1>
      <p></p>
        <table class="table table-bordered">
          <thead>
            <tr>
              <th>Name</th>
              <th>School</th>
              <th>Grade</th>
            </tr>
          </thead>
          <tbody>
            {% if object_list %}
            {% for s in object_list %}
            <tr>
              <td><a href="/students/{{ s.id }}">{{ s }}</a></td>
              <td>{{ s.school }}</td>
              <td>{{ s.grade  }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
              <td></td>
              <td></td>
              <td></td>
            </tr>
            {% endif %}
          </tbody>
        </table>
      <p></p>
    </div>

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{{ STATIC_PREFIX }}js/bootstrap.js"></script>

  </body>
</html>